apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgress-service
    app: demo-microservice
spec:
  selector:
      name: postgress-pod
      app: demo-microservice 
  ports:
    - port: 5432  
      targetPort: 5432
