apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-microservice
spec:
  selector:
      name: redis-pod
      app: demo-microservice 
  ports:
    - port: 6379  
      targetPort: 6379
