apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-srvc
    app: demo-microservice    
spec:
  type: NodePort
  selector:
      name: result-pod
      app: demo-microservice     
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
