apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-microservice      
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-microservice 
    spec:
      containers:
        - name: voting-app-container
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80