apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: demo-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: demo-microservice      
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-microservice 
    spec:
      containers:
        - name: worker-container
          image: kodekloud/examplevotingapp_worker:v1
